// Pi writes each conversation as an append-only JSONL tree under ~/.pi/agent/sessions, so SuperLcm
// indexes the file itself, byte for byte (every branch, tool result and compaction entry included).
// A small Pi extension (written by setup) reports each finished turn and exposes SuperLcm's MCP tools.
import { closeSync, existsSync, openSync, readSync, realpathSync, statSync } from 'node:fs'
import { relative, isAbsolute, sep } from 'node:path'
import { configFiles } from './harness.js'
const inside = (root, file) => { const rel = relative(root, file); return rel && rel !== '..' && !rel.startsWith('..' + sep) && !isAbsolute(rel) }
export const piSessionKey = id => 'pi-' + id
function head(file) {
  const fd = openSync(file, 'r')
  try { const buf = Buffer.alloc(Math.min(statSync(file).size, 64 * 1024)); const n = readSync(fd, buf, 0, buf.length, 0); return JSON.parse(buf.subarray(0, n).toString('utf8').split('\n')[0]) } finally { closeSync(fd) }
}
function sessionName(file) {
  // The latest session_info name, if the user named the conversation in Pi.
  let name = null
  try { for (const line of require_lines(file)) { if (line.includes('"session_info"')) { const x = JSON.parse(line); if (x.type === 'session_info' && typeof x.name === 'string') name = x.name } } } catch {}
  return name
}
function require_lines(file) {
  const size = statSync(file).size, fd = openSync(file, 'r')
  try { const buf = Buffer.alloc(Math.min(size, 32 * 1024 * 1024)); const n = readSync(fd, buf, 0, buf.length, 0); return buf.subarray(0, n).toString('utf8').split('\n') } finally { closeSync(fd) }
}
export function capturePi(store, { session_id: id, session_file: path }, { env = process.env, automatic = false } = {}) {
  if (typeof id !== 'string' || !/^[\w.-]{1,190}$/.test(id)) throw new Error('Invalid Pi session id')
  const session = piSessionKey(id)
  if (automatic && store.isDeleted(session)) return { session, skipped: 'deleted' }
  if (typeof path !== 'string' || !existsSync(path)) return { session, skipped: 'not_written_yet' } // Pi writes the file after the first answer
  const root = realpathSync(configFiles('pi', env).transcripts), file = realpathSync(path)
  if (!inside(root, file)) throw new Error('Pi session file is outside the Pi sessions folder')
  const header = head(file)
  if (header?.type !== 'session' || header.id !== id) throw new Error('Pi session file does not belong to this session')
  const result = store.ingest(session, file)
  const name = sessionName(file)
  store.setMetadata(session, { harness: 'pi', externalId: id, name: name || null, nameSource: name ? 'native' : 'derived' })
  return { ...result, session }
}
// The extension Pi auto-discovers from ~/.pi/agent/extensions. It never calls a model.
export function piExtension({ node, script, home }) {
  const q = JSON.stringify
  return `// SuperLcm for Pi — generated by SuperLcm setup; edits are overwritten on the next setup.
// Saves every finished turn to SuperLcm and gives Pi's AI the SuperLcm tools (lcm_find, lcm_read, ...).
import { spawn } from "node:child_process";
const NODE = ${q(node)}, CLI = ${q(script)}, HOME = ${q(home)};
function report(ctx, event) {
  const sessionId = ctx.sessionManager.getSessionId(), sessionFile = ctx.sessionManager.getSessionFile();
  if (!sessionId) return;
  const child = spawn(NODE, [CLI, "pi-hook", "--home", HOME], { stdio: ["pipe", "ignore", "ignore"], detached: true, windowsHide: true });
  child.on("error", () => {});
  child.stdin.on("error", () => {});
  child.stdin.end(JSON.stringify({ hook_event_name: event, session_id: sessionId, session_file: sessionFile }));
  child.unref();
}
// Minimal MCP client over stdio for the SuperLcm server.
function mcpClient() {
  const proc = spawn(NODE, [CLI, "mcp"], { stdio: ["pipe", "pipe", "ignore"], env: { ...process.env, SUPERLCM_HOME: HOME }, windowsHide: true });
  let buf = "", id = 0; const waiting = new Map();
  proc.stdout.on("data", d => { buf += d; let i; while ((i = buf.indexOf("\\n")) >= 0) { const line = buf.slice(0, i); buf = buf.slice(i + 1); try { const m = JSON.parse(line); const w = waiting.get(m.id); if (w) { waiting.delete(m.id); m.error ? w.reject(new Error(m.error.message)) : w.resolve(m.result); } } catch {} } });
  proc.on("exit", () => { for (const w of waiting.values()) w.reject(new Error("SuperLcm MCP server exited")); waiting.clear(); });
  const call = (method, params) => new Promise((resolve, reject) => { const n = ++id; waiting.set(n, { resolve, reject }); proc.stdin.write(JSON.stringify({ jsonrpc: "2.0", id: n, method, params }) + "\\n"); });
  const notify = (method, params) => proc.stdin.write(JSON.stringify({ jsonrpc: "2.0", method, params }) + "\\n");
  return { proc, call, notify };
}
export default function (pi) {
  let client = null, registered = [];
  pi.on("session_start", async (_event, ctx) => {
    report(ctx, "session_start");
    if (client) return;
    try {
      client = mcpClient();
      await client.call("initialize", { protocolVersion: "2025-06-18", capabilities: {}, clientInfo: { name: "pi", version: "superlcm-extension" } });
      client.notify("notifications/initialized", {});
      const { tools } = await client.call("tools/list", {});
      for (const tool of tools) {
        if (registered.includes(tool.name)) continue;
        pi.registerTool({ name: tool.name, label: tool.name, description: tool.description || tool.name, parameters: tool.inputSchema || { type: "object", properties: {} },
          async execute(_id, params) {
            const result = await client.call("tools/call", { name: tool.name, arguments: params || {} });
            return { content: (result.content || []).filter(c => c.type === "text").map(c => ({ type: "text", text: c.text })), details: {} };
          } });
        registered.push(tool.name);
      }
    } catch (error) { ctx.ui?.notify?.("SuperLcm tools unavailable: " + error.message, "warning"); }
  });
  for (const event of ["turn_end", "agent_settled", "session_compact"]) pi.on(event, async (_event, ctx) => report(ctx, event));
  pi.on("session_shutdown", async (_event, ctx) => { report(ctx, "session_shutdown"); try { client?.proc.kill(); } catch {} client = null; });
  pi.registerCommand("superlcm-status", { description: "Show whether SuperLcm is loaded", handler: async (_args, ctx) => {
    const tools = pi.getActiveTools().filter(n => n.startsWith("lcm_"));
    ctx.ui.notify("SuperLcm tools: " + (tools.join(",") || "none"), "info");
  } });
}
`
}
