// SuperLcm workbench: warm palette and hover/selected states adapted from the local 8790 asset center.
// Conversation labels and summaries are escaped or placed with textContent.
export function page(token,nonce) { return `<!doctype html><html lang="zh"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SuperLcm</title><style>
:root{--bg:#f0eee6;--bg2:#e8e6dc;--surface:#f7f6f1;--ink:#141413;--ink2:#5e5d59;--ink3:#9a9890;--line:#dcd9cf;--accent:#d97757;--accent-deep:#c2613f;--accent-soft:#f3e3da;--good:#4f7a4a;--warn:#a8792a;--bad:#b04a3c;--serif:"Noto Serif SC","Songti SC",Georgia,serif;--sans:"Noto Sans SC",-apple-system,"PingFang SC",sans-serif;--mono:"IBM Plex Mono",ui-monospace,Menlo,monospace;--dur:.18s}
@media(prefers-color-scheme:dark){:root{--bg:#1f1e1b;--bg2:#262521;--surface:#272622;--ink:#ece9e1;--ink2:#aca89e;--ink3:#6f6c64;--line:#36342e;--accent:#e08a6b;--accent-deep:#d97757;--accent-soft:#3a2b24;--good:#8fbf87;--warn:#d1a552;--bad:#e08579}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.75 var(--sans)}button,input,select{font:inherit;color:var(--ink)}button{cursor:pointer}
.page{max-width:1480px;min-height:100vh;margin:auto;padding:0 40px;display:grid;grid-template-columns:238px minmax(0,1fr);gap:40px}
.intro{position:sticky;top:0;height:100vh;padding:31px 18px 24px 0;border-right:1px solid var(--line)}.intro h1{font:400 28px/1.3 var(--serif);margin:0 0 42px}
.side-nav{display:grid;align-content:start;gap:7px}.nav-link{width:100%;min-height:48px;display:flex;justify-content:space-between;align-items:center;text-align:left;padding:8px 13px;border:1px solid var(--line);border-radius:12px;background:var(--surface);transition:border-color var(--dur),background var(--dur)}.nav-link span{font-size:14px;font-weight:500}.nav-link i{display:block;flex:none;width:10px;height:10px;border:1.5px solid var(--ink3);border-radius:50%;transition:border-color var(--dur),background var(--dur)}
.nav-link:hover{border-color:var(--accent)}.nav-link:hover i{background:var(--accent);border-color:var(--accent)}.nav-link.active{background:var(--accent-soft);border-color:var(--accent)}.nav-link.active i{background:var(--accent);border-color:var(--accent)}.nav-link:focus-visible{outline:2px solid var(--accent);outline-offset:3px}
main{min-width:0;padding:48px 0 90px}.chapter{min-width:0}.chapter[hidden]{display:none!important}.head{padding:0 0 24px;margin:0 0 26px;border-bottom:1px solid var(--line)}h2{font:400 29px/1.3 var(--serif);margin:0}.sub{display:block;color:var(--ink3);font:13px/1.6 var(--sans);margin-top:7px}
.tiles{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:10px}.tile,.panel{background:var(--surface);border:1px solid var(--line);border-radius:17px;padding:16px 18px}.tile .k{color:var(--ink2);font-size:13px}.tile .v{font:400 29px/1.3 var(--serif);margin:5px 0}.tile .m{color:var(--ink3);font-size:12px}.panel{margin-top:12px;padding:23px}.panel h3{font:400 23px var(--serif);margin:0 0 12px}
.row{display:flex;align-items:center;flex-wrap:wrap;gap:10px;margin:10px 0}.field{display:grid;gap:5px;min-width:190px;flex:1;color:var(--ink2);font-size:13px}.field input,.field select,input[type=search]{width:100%;padding:9px 12px;border:1px solid var(--line);border-radius:11px;background:var(--bg);outline:none}.field input:focus,.field select:focus,input:focus{border-color:var(--accent)}.btn{padding:8px 16px;border:1px solid var(--line);border-radius:999px;background:var(--surface)}.btn:hover{border-color:var(--accent)}.btn.primary{background:var(--accent);border-color:var(--accent);color:#fff}.btn:disabled{opacity:.5}
.mono{font:12px/1.6 var(--mono);overflow-wrap:anywhere}.muted{color:var(--ink3)}.good{color:var(--good)}.warn{color:var(--warn)}.bad{color:var(--bad)}.record{border-top:1px solid var(--line);padding:9px 0;font-size:13px}.record b{font-weight:500}.pre{background:var(--bg2);border-radius:12px;padding:14px;white-space:pre-wrap;word-break:break-word;font:12px/1.6 var(--mono);max-height:190px;overflow:auto}.tag{padding:3px 8px;border-radius:99px;background:var(--accent-soft);font-size:11px;color:var(--accent-deep)}
@media(max-width:900px){.page{grid-template-columns:196px minmax(0,1fr);gap:22px;padding:0 20px}.intro{padding-right:12px}}
@media(max-width:640px){.page{grid-template-columns:103px minmax(0,1fr);gap:10px;padding:0 12px}.intro{padding:18px 5px 15px 0}.intro h1{font-size:15px;margin-bottom:24px}.nav-link{min-height:44px;padding:5px 6px;border-radius:10px}.nav-link span{font-size:11px;white-space:nowrap}.nav-link i{width:7px;height:7px}main{padding:22px 0 55px}h2{font-size:23px}.head{padding-bottom:15px;margin-bottom:17px}.tiles{grid-template-columns:1fr}.tile,.panel{padding:14px}.field{min-width:150px}}
@media(prefers-reduced-motion:reduce){.nav-link,.nav-link i{transition:none}}
</style></head><body><div class="page"><aside class="intro"><h1>SuperLcm</h1><nav class="side-nav" aria-label="控制台菜单"><button type="button" class="nav-link active" data-view="assets" aria-controls="view-assets" aria-current="page"><span>对话资产</span><i aria-hidden="true"></i></button><button type="button" class="nav-link" data-view="delivery" aria-controls="view-delivery"><span>定向投递</span><i aria-hidden="true"></i></button><button type="button" class="nav-link" data-view="summary" aria-controls="view-summary"><span>摘要策略</span><i aria-hidden="true"></i></button><button type="button" class="nav-link" data-view="connection" aria-controls="view-connection"><span>连接诊断</span><i aria-hidden="true"></i></button></nav></aside><main id="workbench"><section class="chapter" id="view-assets" data-view-panel="assets"><div class="head"><h2>对话资产<span class="sub">来源、名称、原始 ID 与摘要数量</span></h2></div><div class="row"><input id="filter" type="search" placeholder="筛选已加载的名称或 ID" aria-label="筛选对话"><button class="btn" id="refresh">刷新</button></div><div class="tiles" id="stats"></div><div class="panel"><h3>已索引的对话</h3><div id="sessions" class="muted">读取中…</div><button class="btn" id="more" style="display:none">加载更多</button></div></section>
<section class="chapter" id="view-delivery" data-view-panel="delivery" hidden><div class="head"><h2>定向投递<span class="sub">源对话 → 目标对话 · 下次 hook 提供导航</span></h2></div><div class="panel"><div class="row"><label class="field">摘要来源<select id="source"></select></label><label class="field">接收的对话<select id="target"></select></label></div><div class="row"><button class="btn" id="preview">预览导航</button><button class="btn primary" id="send">加入待投递</button></div><div class="pre" id="previewtext">先选择来源再预览。</div><p class="muted" style="font-size:12px">MCP 的 lcm_context 可直接把导航带入调用工具的智能体；跨对话投递必须等目标的 UserPromptSubmit / SessionStart hook 领取。</p></div><div class="panel"><h3>投递回执</h3><div id="deliveries" class="muted">暂无</div></div></section>
<section class="chapter" id="view-summary" data-view-panel="summary" hidden><div class="head"><h2>摘要策略<span class="sub">主会话写摘要默认关闭 · 模型调用需要主动启用</span></h2></div><div class="panel"><div class="row"><label class="field">选择对话<select id="modeSession"></select></label><label class="field">写摘要的执行方<select id="mode"><option value="auto">继承全局 auto（有专用 API 密钥时走 API）</option><option value="off">关闭摘要</option><option value="cli">后台 Claude CLI</option><option value="codex-cli">后台 Codex CLI</option><option value="api">独立 API</option><option value="agent">当前会话智能体 · 尽力而为</option></select></label><label class="field">模型名（留空用执行方默认）<input id="model" type="text" maxlength="128" placeholder="例如 sonnet / 自己的 Codex 模型"></label></div><button id="saveMode" class="btn primary">保存此对话策略</button><p class="muted" style="font-size:12px">agent 需要对应 UserPromptSubmit hook；由模型决定是否调用摘要工具，不能保证完成。Codex/Claude CLI 分别使用各自本机登录；API 须在服务环境配置独立凭据。这里只保存策略，不触发模型。</p></div></section>
<section class="chapter" id="view-connection" data-view-panel="connection" hidden><div class="head"><h2>连接诊断<span class="sub">测试 MCP 协议，区分握手与宿主真实活动</span></h2></div><div class="panel"><div class="row"><button id="probe" class="btn primary">测试 MCP 服务</button><span id="probeResult" class="muted">尚未测试</span></div><div id="clients" class="muted">尚无连接记录</div><p class="muted" style="font-size:12px">自检只证明本机 MCP 能初始化和列工具；Claude/Codex 是否实际配置及调用，以各自 hook / MCP 最近活动为准。客户端名称由其自行报告，不是身份认证。</p></div></section></main></div><script nonce="${nonce}">
const token=${JSON.stringify(token)};history.replaceState(null,'','/'+location.hash);const $=id=>document.getElementById(id);const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let sessions=[],offset=0,total=0;
async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});const x=await r.json();if(!r.ok)throw Error(x.error||'请求失败');return x}
const label=s=>s.harness+' · '+s.name+' · '+s.conversation_id;function options(id){const el=$(id),prev=el.value;el.innerHTML=sessions.map(s=>'<option value="'+esc(s.session)+'">'+esc(label(s))+'</option>').join('');if(sessions.some(s=>s.session===prev))el.value=prev}
function render(){const q=$('filter').value.toLowerCase();const visible=sessions.filter(s=>label(s).toLowerCase().includes(q));$('stats').innerHTML='<div class="tile"><div class="k">已索引</div><div class="v">'+total+'</div><div class="m">份独立源对话</div></div><div class="tile"><div class="k">本页有摘要</div><div class="v">'+sessions.filter(s=>s.summary_count).length+'</div><div class="m">可选择投递</div></div>'; $('sessions').innerHTML=visible.length?visible.map(s=>'<div class="record"><b>'+esc(s.name)+'</b> <span class="tag">'+esc(s.harness)+'</span><div class="mono muted">'+esc(s.conversation_id)+' · 索引 '+esc(s.session)+' · '+s.summary_count+' 个摘要 · '+esc(s.status)+'</div></div>').join(''):'没有匹配的已加载对话';for(const id of ['source','target','modeSession'])options(id);$('more').style.display=offset<total?'inline-block':'none'}
async function load(reset=false){if(reset){sessions=[];offset=0}const x=await api('/api/sessions?offset='+offset);sessions.push(...x.sessions);offset=x.next_offset??x.total;total=x.total;render();const state=await api('/api/state');$('deliveries').innerHTML=state.deliveries.length?state.deliveries.map(d=>'<div class="record mono">#'+d.id+' · '+esc(d.source_session)+' → '+esc(d.target_session)+' · '+(d.issued_at?'<span class="good">hook 已发出，未证明模型已读取</span>':'<span class="warn">待目标 hook 领取</span>')+'</div>').join(''):'暂无投递';$('clients').innerHTML=['claude-code','codex'].map(h=>{const hook=state.clients.find(c=>c.client===h&&c.kind==='hook'),mcp=state.clients.find(c=>c.kind==='mcp-self-reported'&&c.client.toLowerCase().includes(h==='claude-code'?'claude':'codex'));const age=c=>c&&Date.now()-Date.parse(c.seen_at.replace(' ','T')+'Z')<600000;return '<div class="record"><b>'+esc(h)+'</b> · '+(age(hook)?'<span class="good">近 10 分钟有 hook 活动</span>':hook?'<span class="warn">历史 hook · '+esc(hook.seen_at)+'</span>':'未见 hook 活动')+' · '+(age(mcp)?'<span class="good">MCP 最近自报握手</span>':mcp?'<span class="warn">历史 MCP 自报</span>':'未见该客户端 MCP 自报')+'</div>'}).join('')+(state.clients.some(c=>c.client==='web-self-test')?'<div class="record muted">本机协议自检已运行；不代表 Claude/Codex 已连通</div>':'')}
async function act(fn){try{await fn()}catch(e){alert(e.message)}}$('filter').oninput=render;$('refresh').onclick=()=>act(()=>load(true));$('more').onclick=()=>act(()=>load());$('preview').onclick=()=>act(async()=>{$('previewtext').textContent=(await api('/api/context?session='+encodeURIComponent($('source').value))).content});$('send').onclick=()=>act(async()=>{const x=await api('/api/deliver',{source:$('source').value,target:$('target').value});alert('已排队 #'+x.id+'；目标下一次 hook 才能领取。');await load(true)});$('modeSession').onchange=()=>act(async()=>{const x=await api('/api/preference?session='+encodeURIComponent($('modeSession').value));$('mode').value=x.mode;$('model').value=x.model||'';modeField()});function modeField(){const agent=$('mode').value==='agent'||$('mode').value==='off';$('model').disabled=agent;$('model').placeholder=agent?'由当前会话决定 / 关闭时不使用':'例如 sonnet / 自己的 Codex 模型'}$('mode').onchange=modeField;modeField();$('saveMode').onclick=()=>act(async()=>{await api('/api/preference',{session:$('modeSession').value,mode:$('mode').value,model:$('model').disabled?null:($('model').value||null)});alert('策略已保存；没有启动模型。')});$('probe').onclick=()=>act(async()=>{$('probeResult').textContent='测试中…';const x=await api('/api/probe',{});$('probeResult').textContent=x.ok?'协议握手和工具清单成功（不是宿主连接证明）':x.error});const viewNames=['assets','delivery','summary','connection'];function showView(view,updateHash=true){if(!viewNames.includes(view))view='assets';for(const button of document.querySelectorAll('.nav-link')){const active=button.dataset.view===view;button.classList.toggle('active',active);if(active)button.setAttribute('aria-current','page');else button.removeAttribute('aria-current')}for(const panel of document.querySelectorAll('[data-view-panel]'))panel.hidden=panel.dataset.viewPanel!==view;if(updateHash)history.replaceState(null,'','#'+view);window.scrollTo({top:0,behavior:'instant'})}for(const button of document.querySelectorAll('.nav-link'))button.addEventListener('click',()=>showView(button.dataset.view));window.addEventListener('hashchange',()=>showView(location.hash.slice(1),false));showView(location.hash.slice(1)||'assets');load(true).then(()=>{if(sessions.length)$('modeSession').onchange()}).catch(e=>{$('sessions').textContent=e.message});
</script></body></html>` }
