history.replaceState(null,'','/'+location.hash);
const $=id=>document.getElementById(id);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let harnessRecords=[],sessions=[],indexHarness='',indexOffset=0,indexTotal=0,localHarness='codex',localOffset=0,localRows=[],summaryCursor=null,summarySession=null,setupChoice=null;
let currentDeliveryId=null,previewedSource=null;
const picks={source:{rows:[],offset:0},target:{rows:[],offset:0}};
async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});const x=await r.json();if(!r.ok)throw Error(x.error||'请求失败');return x}
async function act(fn,button){$('error').hidden=true;if(button)button.disabled=true;try{return await fn()}catch(e){$('error').textContent=e.message;$('error').hidden=false;$('error').scrollIntoView({block:'start'})}finally{if(button)button.disabled=false}}
const label=h=>harnessRecords.find(x=>x.harness===h)?.label||h;
const q=x=>encodeURIComponent(x);
function setOptions(id,rows,extra=''){const el=$(id),previous=el.value;el.innerHTML=extra+rows.map(([value,text])=>'<option value="'+esc(value)+'">'+esc(text)+'</option>').join('');if(rows.some(([v])=>v===previous))el.value=previous}
function tabs(id,selected,choices,fn){$(id).innerHTML=choices.map(([key,name])=>'<button class="chip" aria-selected="'+(key===selected)+'" data-harness="'+esc(key)+'">'+esc(name)+'</button>').join('');for(const b of $(id).querySelectorAll('button'))b.onclick=()=>act(()=>fn(b.dataset.harness),b)}
async function detect(){const data=await api('/api/harnesses');harnessRecords=data.harnesses;$('detectionTime').textContent='检测时间 '+new Date().toLocaleTimeString();renderConnections();await updateGroups()}
async function updateGroups(){const counts=await api('/api/statistics');$('stats').innerHTML=[['已索引',counts.sessions,'份独立对话'],['摘要',counts.summaries,'个实际保存节点']].map(([k,n,unit])=>'<div class="tile"><div class="k">'+k+'</div><div class="v">'+n+'</div><div class="m">'+unit+'</div></div>').join('');const groups=[...new Set([...harnessRecords.filter(h=>h.detected).map(h=>h.harness),...counts.groups.map(h=>h.harness)])];tabs('indexHarnesses',indexHarness,[['','全部'],...groups.map(h=>[h,label(h)])],async h=>{indexHarness=h;await loadIndex(true);await updateGroups()});const local=harnessRecords.filter(h=>h.local_conversations||h.supported);if(!local.some(h=>h.harness===localHarness))localHarness=local[0]?.harness||'codex';tabs('localHarnesses',localHarness,local.map(h=>[h.harness,h.label+(h.detected?'':' · 未检测到')]),async h=>{localHarness=h;await updateGroups();await loadLocal(true)});for(const side of ['source','target'])setOptions(side+'Harness',counts.groups.map(h=>[h.harness,label(h.harness)+' · '+h.sessions+' 个已入库会话']),'<option value="">选择 harness</option>')}
function renderIndex(){const term=$('filter').value.toLowerCase();const rows=sessions.filter(s=>(s.name+' '+s.conversation_id).toLowerCase().includes(term));$('sessions').innerHTML=rows.length?rows.map(s=>'<div class="record"><div class="row"><b>'+esc(s.name)+'</b><span class="tag">'+esc(label(s.harness))+'</span></div><div class="mono muted">'+esc(s.conversation_id)+' · '+s.summary_count+' 个摘要 · '+esc(s.status)+'</div><div class="actions"><button class="btn" data-detail="'+esc(s.session)+'">查看摘要</button><button class="btn" data-use-source="'+esc(s.session)+'" '+(!s.summary_count?'disabled':'')+'>导入到其他对话</button><button class="btn" data-check="'+esc(s.session)+'">验证原文指针</button></div><div class="small" data-result="'+esc(s.session)+'"></div></div>').join(''):'<div class="empty">没有匹配的已索引对话。已配置的采集 hook 会写入新会话；必要时可展开下方采集管理。</div>';$('indexCount').textContent='已加载 '+sessions.length+' / '+indexTotal+'，名称筛选仅针对已加载记录';$('more').hidden=indexOffset===null;for(const b of $('sessions').querySelectorAll('[data-use-source]'))b.onclick=()=>act(async()=>{const source=sessions.find(x=>x.session===b.dataset.useSource);showView('delivery');$('sourceHarness').value=source.harness;await loadPicker('source',true);if(!picks.source.rows.some(x=>x.session===source.session)){picks.source.rows.push(source);$('source').insertAdjacentHTML('beforeend','<option value="'+esc(source.session)+'">'+esc(source.name)+'</option>')}$('source').value=source.session;updateDeliveryButtons();await previewSource()},b);for(const b of $('sessions').querySelectorAll('[data-detail]'))b.onclick=()=>act(()=>loadNodes(b.dataset.detail,true),b);for(const b of $('sessions').querySelectorAll('[data-check]'))b.onclick=()=>act(async()=>{const x=await api('/api/doctor?session='+q(b.dataset.check));b.parentElement.nextElementSibling.textContent=x.issues.length?'原文验证失败：'+x.issues.join('；'):'原文指针完整：'+x.events+' 条记录，'+x.nodes+' 个节点'},b)}
async function loadIndex(reset=false){if(reset){indexOffset=0;sessions=[]}if(indexOffset===null)return;const x=await api('/api/sessions?offset='+indexOffset+(indexHarness?'&harness='+q(indexHarness):''));sessions.push(...x.sessions);indexOffset=x.next_offset;indexTotal=x.total;renderIndex();await updateGroups()}
async function loadNodes(session,reset){if(reset){summarySession=session;summaryCursor=0;$('summaryNodes').innerHTML='';$('summaryTitle').textContent='摘要 · '+(sessions.find(x=>x.session===session)?.name||session)}const x=await api('/api/summary-nodes?session='+q(session)+'&offset='+summaryCursor);$('summaryPanel').hidden=false;$('summaryNodes').insertAdjacentHTML('beforeend',x.nodes.length?x.nodes.map(n=>'<div class="record"><div class="small muted">L'+n.level+' · '+esc(n.model)+' · '+n.first+'–'+n.last+'</div><div class="pre tall">'+esc(n.summary)+'</div></div>').join(''):'<p class="muted">此会话尚无摘要。已有原文不等于已生成摘要。</p>');summaryCursor=x.next_offset;$('moreNodes').hidden=summaryCursor===null}
async function loadLocal(reset=false){if(reset){localOffset=0;localRows=[]}$('localSessions').setAttribute('aria-busy','true');const x=await api('/api/local-conversations?harness='+q(localHarness)+'&offset='+localOffset);localRows.push(...x.conversations);localOffset=x.next_offset;$('localRoot').textContent=x.root;$('localCount').textContent='已加载 '+localRows.length+' / '+x.total+(x.scan_limited?' · 扫描达到安全上限':'');$('localMore').hidden=localOffset===null;$('localSessions').innerHTML=localRows.length?localRows.map(s=>'<div class="record"><div class="row"><b>'+esc(s.name)+'</b><button class="btn" data-index="'+esc(s.key)+'" '+(!s.can_index?'disabled':'')+'>'+(s.import_kind==='snapshot'?'导入只读快照':s.indexed?'更新索引':'索引此对话')+'</button></div><div class="mono muted">'+esc(s.conversation_id)+' · '+Math.ceil(s.bytes/1024)+' KiB · '+esc(s.updated_at)+'</div><div class="small '+(s.error?'bad':'muted')+'">'+esc(s.error||(s.indexed?'已入库 · '+s.summary_count+' 个摘要':'未入库'))+'</div></div>').join(''):'<div class="empty">该 harness 未找到本地会话。远程 / SSH 会话不在此计算机。</div>';$('localSessions').removeAttribute('aria-busy');for(const b of $('localSessions').querySelectorAll('[data-index]'))b.onclick=()=>act(async()=>{const x=await api('/api/index-local',{harness:localHarness,key:b.dataset.index});$('localFeedback').textContent=x.source.name+'：新增 '+x.added+' 条原文，'+x.summary_count+' 个摘要。'+x.note;await loadLocal(true);await loadIndex(true);for(const side of ['source','target'])if($(side+'Harness').value)await loadPicker(side,true)},b)}
async function loadPicker(side,reset=false){const h=$(side+'Harness').value;if(reset)picks[side]={rows:[],offset:0};if(!h){$(side).innerHTML='<option value="">先选 harness</option>';updateDeliveryButtons();return}const state=picks[side],previous=$(side).value;if(state.offset!==null){const x=await api('/api/sessions?harness='+q(h)+'&offset='+state.offset);state.rows.push(...x.sessions);state.offset=x.next_offset}$(side).innerHTML='<option value="">选择对话</option>'+state.rows.map(s=>'<option value="'+esc(s.session)+'" '+(side==='source'&&!s.summary_count?'disabled':'')+'>'+esc(s.name)+' · '+esc(s.conversation_id)+' · '+s.summary_count+' 个摘要</option>').join('');if(state.rows.some(s=>s.session===previous))$(side).value=previous;$(side+'More').hidden=state.offset===null;updateDeliveryButtons()}
function updateDeliveryButtons(){const from=$('source').value;if(from!==previewedSource)$('previewtext').textContent=from?'点击预览查看所选索引会话的摘要导航。':'选择有摘要的来源再预览。';const to=$('target').value,recipient=harnessRecords.find(h=>h.harness===$('targetHarness').value);if($('targetHarness').value&&!recipient?.supported&&$('deliveryRoute').value==='hook')$('deliveryRoute').value='mcp';$('preview').disabled=!from;$('send').disabled=!from||!to||from===to;$('deliveryHint').textContent=from&&to&&from===to?'来源与目标是同一会话，请选择另一个接收对话。':$('deliveryRoute').value==='mcp'?'确认后保存为待领取导入；目标智能体需要调用 lcm_receive_context，不冒充已经写入目标上下文。':'确认后进入导入队列；目标 hook 在其下次发言/启动时接收。若 hook 未启用或未信任，则会保持待领取。';$('directInstruction').textContent=from?'请调用 SuperLcm 的 lcm_context 工具，参数 '+JSON.stringify({session:from})+'，把返回的来源摘要导航用于当前对话；需要完整摘要时继续调用 lcm_summaries，并按原文指针验证关键事实。':'先选择索引库中的来源对话。';$('copyInstruction').disabled=!from}
async function previewSource(){const selected=$('source').value;const x=await api('/api/context?session='+q(selected));if($('source').value!==selected)return;previewedSource=selected;$('previewtext').textContent=x.content+'\n\n—— 共 '+x.summary_nodes+' 个摘要节点；当前为限长导航'+(x.truncated?'（已截断，可经 lcm_summaries 继续读取）':'')+'。'}
async function loadReceipts(){const x=await api('/api/state');const current=x.deliveries.find(d=>d.id===currentDeliveryId);if(current?.issued_at)$('deliveryFeedback').textContent='导入 #'+current.id+'：'+(current.status==='mcp_received'?'目标 MCP 已领取摘要上下文。':'hook 已发出摘要上下文，尚未证明宿主读取。');$('deliveries').innerHTML=x.deliveries.length?x.deliveries.map(d=>'<div class="record"><div><b>'+esc(d.source.name)+'</b> → <b>'+esc(d.target.name)+'</b></div><div class="mono muted">#'+d.id+' · '+esc(d.source_session)+' → '+esc(d.target_session)+'</div><span class="small '+(d.issued_at?'good':'warn')+'">'+(d.status==='mcp_received'?'目标 MCP 已领取 · 不等于模型已采纳':d.issued_at?'hook 已发出 · 未证明宿主已读取':d.delivery_route==='mcp'?'待目标 MCP 领取':'待目标 hook 接收')+'</span>'+(!d.issued_at?'<div class="small muted">也可在目标会话要求调用 lcm_receive_context，参数 '+esc(JSON.stringify({target:d.target_session}))+'</div>':'')+'</div>').join(''):'<div class="empty">暂无跨对话导入记录</div>'}
$('scanLocal').onclick=()=>act(()=>loadLocal(true),$('scanLocal'));$('localMore').onclick=()=>act(()=>loadLocal(),$('localMore'));
$('filter').oninput=renderIndex;$('refresh').onclick=()=>act(()=>loadIndex(true),$('refresh'));$('more').onclick=()=>act(()=>loadIndex(),$('more'));$('moreNodes').onclick=()=>act(()=>loadNodes(summarySession,false),$('moreNodes'));
for(const side of ['source','target']){$(side+'Harness').onchange=()=>act(()=>loadPicker(side,true));$(side).onchange=updateDeliveryButtons;$(side+'More').onclick=()=>act(()=>loadPicker(side),$(side+'More'))}
$('preview').onclick=()=>act(previewSource,$('preview'));
$('deliveryRoute').onchange=updateDeliveryButtons;
$('refreshDeliveries').onclick=()=>act(loadReceipts,$('refreshDeliveries'));
$('copyInstruction').onclick=()=>act(async()=>{try{await navigator.clipboard.writeText($('directInstruction').textContent);$('copyFeedback').textContent='已复制，请交给目标对话'}catch{$('copyFeedback').textContent='浏览器不允许复制，请直接选中上方指令'}},$('copyInstruction'));
$('send').onclick=()=>act(async()=>{const x=await api('/api/deliver',{source:$('source').value,target:$('target').value,route:$('deliveryRoute').value});currentDeliveryId=x.id;$('deliveryFeedback').textContent='导入 #'+x.id+' 已保存为待领取；尚未写入目标上下文。'+(x.route==='mcp'?'在目标会话调用 lcm_receive_context，参数 '+JSON.stringify({target:x.target.session}):'等待目标下次发言时 hook 接收。');await loadReceipts()},$('send'));
const viewNames=['assets','delivery','summary','connection'];function showView(view,updateHash=true){if(!viewNames.includes(view))view='assets';for(const b of document.querySelectorAll('.nav-link')){const active=b.dataset.view===view;b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')}for(const p of document.querySelectorAll('[data-view-panel]'))p.hidden=p.dataset.viewPanel!==view;if(updateHash)history.replaceState(null,'','#'+view);window.scrollTo({top:0,behavior:'instant'})}
for(const b of document.querySelectorAll('.nav-link'))b.onclick=()=>showView(b.dataset.view);window.addEventListener('hashchange',()=>showView(location.hash.slice(1),false));showView(location.hash.slice(1)||'assets');
(async()=>{await detect();await Promise.all([loadIndex(true),loadReceipts(),loadSettings()]);updateDeliveryButtons()})().catch(e=>{$('error').textContent=e.message;$('error').hidden=false});

let polling=false;setInterval(async()=>{if(polling||document.visibilityState!=='visible')return;polling=true;try{if(location.hash==='#delivery')await loadReceipts();if(location.hash==='#connection')await refreshConnectionEvidence()}catch{}finally{polling=false}},5000);
