history.replaceState(null,'','/'+location.hash);
const $=id=>document.getElementById(id);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let harnessRecords=[],sessions=[],indexHarness='',indexOffset=0,indexTotal=0,localHarness='codex',localOffset=0,localRows=[],summaryCursor=null,summarySession=null,setupChoice=null;
const picks={source:{rows:[],offset:0},target:{rows:[],offset:0}};
async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});const x=await r.json();if(!r.ok)throw Error(x.error||'请求失败');return x}
async function act(fn,button){$('error').hidden=true;if(button)button.disabled=true;try{return await fn()}catch(e){$('error').textContent=e.message;$('error').hidden=false}finally{if(button)button.disabled=false}}
const label=h=>harnessRecords.find(x=>x.harness===h)?.label||h;
const q=x=>encodeURIComponent(x);
function setOptions(id,rows,extra=''){const el=$(id),previous=el.value;el.innerHTML=extra+rows.map(([value,text])=>'<option value="'+esc(value)+'">'+esc(text)+'</option>').join('');if(rows.some(([v])=>v===previous))el.value=previous}
function tabs(id,selected,choices,fn){$(id).innerHTML=choices.map(([key,name])=>'<button class="chip" aria-selected="'+(key===selected)+'" data-harness="'+esc(key)+'">'+esc(name)+'</button>').join('');for(const b of $(id).querySelectorAll('button'))b.onclick=()=>act(()=>fn(b.dataset.harness),b)}
async function detect(){const data=await api('/api/harnesses');harnessRecords=data.harnesses;$('detectionTime').textContent='检测时间 '+new Date().toLocaleTimeString();renderConnections();await updateGroups()}
async function updateGroups(){const counts=await api('/api/statistics');$('stats').innerHTML=[['已索引',counts.sessions,'份独立对话'],['摘要',counts.summaries,'个实际保存节点']].map(([k,n,unit])=>'<div class="tile"><div class="k">'+k+'</div><div class="v">'+n+'</div><div class="m">'+unit+'</div></div>').join('');const groups=[...new Set([...harnessRecords.filter(h=>h.detected).map(h=>h.harness),...counts.groups.map(h=>h.harness)])];tabs('indexHarnesses',indexHarness,[['','全部'],...groups.map(h=>[h,label(h)])],async h=>{indexHarness=h;await loadIndex(true);await updateGroups()});const local=harnessRecords.filter(h=>h.local_conversations||h.supported);if(!local.some(h=>h.harness===localHarness))localHarness=local[0]?.harness||'codex';tabs('localHarnesses',localHarness,local.map(h=>[h.harness,h.label+(h.detected?'':' · 未检测到')]),async h=>{localHarness=h;await updateGroups();await loadLocal(true)});for(const side of ['source','target'])setOptions(side+'Harness',groups.map(h=>[h,label(h)]),'<option value="">选择 harness</option>')}
function renderIndex(){const term=$('filter').value.toLowerCase();const rows=sessions.filter(s=>(s.name+' '+s.conversation_id).toLowerCase().includes(term));$('sessions').innerHTML=rows.length?rows.map(s=>'<div class="record"><div class="row"><b>'+esc(s.name)+'</b><span class="tag">'+esc(label(s.harness))+'</span></div><div class="mono muted">'+esc(s.conversation_id)+' · '+s.summary_count+' 个摘要 · '+esc(s.status)+'</div><div class="actions"><button class="btn" data-detail="'+esc(s.session)+'">查看摘要</button><button class="btn" data-check="'+esc(s.session)+'">验证原文指针</button></div><div class="small" data-result="'+esc(s.session)+'"></div></div>').join(''):'<div class="empty">没有匹配的已索引对话。可到「对话导入」选择本地记录。</div>';$('indexCount').textContent='已加载 '+sessions.length+' / '+indexTotal+'，名称筛选仅针对已加载记录';$('more').hidden=indexOffset===null;for(const b of $('sessions').querySelectorAll('[data-detail]'))b.onclick=()=>act(()=>loadNodes(b.dataset.detail,true),b);for(const b of $('sessions').querySelectorAll('[data-check]'))b.onclick=()=>act(async()=>{const x=await api('/api/doctor?session='+q(b.dataset.check));b.parentElement.nextElementSibling.textContent=x.issues.length?'原文验证失败：'+x.issues.join('；'):'原文指针完整：'+x.events+' 条记录，'+x.nodes+' 个节点'},b)}
async function loadIndex(reset=false){if(reset){indexOffset=0;sessions=[]}if(indexOffset===null)return;const x=await api('/api/sessions?offset='+indexOffset+(indexHarness?'&harness='+q(indexHarness):''));sessions.push(...x.sessions);indexOffset=x.next_offset;indexTotal=x.total;renderIndex();await updateGroups()}
async function loadNodes(session,reset){if(reset){summarySession=session;summaryCursor=0;$('summaryNodes').innerHTML='';$('summaryTitle').textContent='摘要 · '+(sessions.find(x=>x.session===session)?.name||session)}const x=await api('/api/summary-nodes?session='+q(session)+'&offset='+summaryCursor);$('summaryPanel').hidden=false;$('summaryNodes').insertAdjacentHTML('beforeend',x.nodes.length?x.nodes.map(n=>'<div class="record"><div class="small muted">L'+n.level+' · '+esc(n.model)+' · '+n.first+'–'+n.last+'</div><div class="pre tall">'+esc(n.summary)+'</div></div>').join(''):'<p class="muted">此会话尚无摘要。已有原文不等于已生成摘要。</p>');summaryCursor=x.next_offset;$('moreNodes').hidden=summaryCursor===null}
async function loadLocal(reset=false){if(reset){localOffset=0;localRows=[]}$('localSessions').setAttribute('aria-busy','true');const x=await api('/api/local-conversations?harness='+q(localHarness)+'&offset='+localOffset);localRows.push(...x.conversations);localOffset=x.next_offset;$('localRoot').textContent=x.root;$('localCount').textContent='已加载 '+localRows.length+' / '+x.total+(x.scan_limited?' · 扫描达到安全上限':'');$('localMore').hidden=localOffset===null;$('localSessions').innerHTML=localRows.length?localRows.map(s=>'<div class="record"><div class="row"><b>'+esc(s.name)+'</b><button class="btn" data-index="'+esc(s.key)+'" '+(!s.can_index?'disabled':'')+'>'+(s.import_kind==='snapshot'?'导入只读快照':s.indexed?'更新索引':'索引此对话')+'</button></div><div class="mono muted">'+esc(s.conversation_id)+' · '+Math.ceil(s.bytes/1024)+' KiB · '+esc(s.updated_at)+'</div><div class="small '+(s.error?'bad':'muted')+'">'+esc(s.error||(s.indexed?'已入库 · '+s.summary_count+' 个摘要':'未入库'))+'</div></div>').join(''):'<div class="empty">该 harness 未找到本地会话。远程 / SSH 会话不在此计算机。</div>';$('localSessions').removeAttribute('aria-busy');for(const b of $('localSessions').querySelectorAll('[data-index]'))b.onclick=()=>act(async()=>{const x=await api('/api/index-local',{harness:localHarness,key:b.dataset.index});$('localFeedback').textContent=x.source.name+'：新增 '+x.added+' 条原文，'+x.summary_count+' 个摘要。'+x.note;await loadLocal(true);await loadIndex(true);for(const side of ['source','target'])if($(side+'Harness').value)await loadPicker(side,true)},b)}
async function loadPicker(side,reset=false){const h=$(side+'Harness').value;if(reset)picks[side]={rows:[],offset:0};if(!h){$(side).innerHTML='<option value="">先选 harness</option>';updateDeliveryButtons();return}const state=picks[side],previous=$(side).value;if(state.offset!==null){const x=await api('/api/sessions?harness='+q(h)+'&offset='+state.offset);state.rows.push(...x.sessions);state.offset=x.next_offset}$(side).innerHTML='<option value="">选择对话</option>'+state.rows.map(s=>'<option value="'+esc(s.session)+'" '+(side==='source'&&!s.summary_count?'disabled':'')+'>'+esc(s.name)+' · '+esc(s.conversation_id)+' · '+s.summary_count+' 个摘要</option>').join('');if(state.rows.some(s=>s.session===previous))$(side).value=previous;$(side+'More').hidden=state.offset===null;updateDeliveryButtons()}
function updateDeliveryButtons(){const from=$('source').value,to=$('target').value,recipient=harnessRecords.find(h=>h.harness===$('targetHarness').value);$('preview').disabled=!from;$('send').disabled=!from||!to||from===to||!recipient?.supported;$('deliveryHint').textContent=!recipient?.supported&&to?'此来源没有自动投递 adapter；可在目标会话使用 MCP lcm_context 直接召回。':'跨对话导入进入待投递队列；目标 hook 下次领取，不表示模型已读取。'}
async function loadReceipts(){const x=await api('/api/state');$('deliveries').innerHTML=x.deliveries.length?x.deliveries.map(d=>'<div class="record"><div class="mono">#'+d.id+' · '+esc(d.source_session)+' → '+esc(d.target_session)+'</div><span class="small '+(d.issued_at?'good':'warn')+'">'+(d.issued_at?'hook 已发出 · 未证明模型已读取':'待目标 hook 领取')+'</span></div>').join(''):'<div class="empty">暂无投递记录</div>'}
const hookLabel=x=>({configured:'5 项已配置',partial:'配置不完整',missing:'未配置',disabled:'已禁用',invalid:'配置无效',unsupported:'暂无 adapter'}[x]||x);
function renderConnections(){$('harnessRows').innerHTML=harnessRecords.map(h=>'<tr><td><b>'+esc(h.label||h.harness)+'</b><div class="small '+(h.detected?'good':'muted')+'">'+(h.detected?'已检测到':'未检测到')+' · '+esc(h.version||'版本未读取')+'</div><div class="mono muted">'+esc(h.bin||'CLI 不在已知路径')+'</div></td><td><span class="'+(h.configuration_matches?'good':'warn')+'">'+(!h.supported?'MCP adapter 未实现':h.configuration_matches?'配置匹配本索引':h.configured?'配置存在但不匹配':'未配置 SuperLcm')+'</span><div class="small muted">宿主连接：尚未证实</div></td><td>'+esc(hookLabel(h.hook.status))+'<div class="small muted">'+esc(h.hook_seen?'最近 hook：'+h.hook_seen:'未见 hook 活动')+'</div><div class="small muted">'+esc(h.mcp_self_reported?'MCP 自报：'+h.mcp_self_reported:'未见该客户端握手')+'</div></td><td><div class="actions"><button class="btn" data-test="'+esc(h.harness)+'" '+(!h.detected&&!h.supported?'disabled':'')+'>测试</button><button class="btn" data-setup="'+esc(h.harness)+'" '+(!h.supported||!h.bin?'disabled':'')+'>接入 / 修复</button></div></td></tr><tr><td colspan="4"><div id="check-'+esc(h.harness)+'" class="small muted">'+esc(h.supported?(h.hook.note||'等待逐项测试'):(h.local_conversations?'已检测；可在对话导入中选择原生记录制作只读快照。MCP/自动 hook 接入尚未适配。':'已识别 CLI，暂不支持自动安装或采集。'))+'</div></td></tr>').join('');for(const b of $('harnessRows').querySelectorAll('[data-test]'))b.onclick=()=>act(async()=>{let el=$('check-'+b.dataset.test);el.textContent='检查配置、协议与隔离 hook 写入中…';const x=await api('/api/harness-test',{harness:b.dataset.test});el=$('check-'+b.dataset.test);if(x.capabilities_only){el.textContent=(x.detected?'CLI 已检测到':'未检测到 CLI')+' · '+(x.version||'')+' · '+(x.local.ok?'本地对话 '+x.local.total+' 个':x.local.error||x.local.note)+'。'+x.note;return}el.innerHTML='<div class="status-list"><span class="'+(x.configuration.ok?'good':'warn')+'">配置：'+(x.configuration.ok?'匹配':'未匹配')+'</span><span class="'+(x.protocol.ok?'good':'warn')+'">MCP：'+esc(x.protocol.ok?'真实握手成功 · '+x.protocol.tool_count+' 个工具':x.protocol.error)+'</span><span class="'+(x.hook.adapter.ok?'good':'bad')+'">Hook 适配器：'+esc(x.hook.adapter.ok?'临时库写入 '+x.hook.adapter.events+' 条，退出码 '+x.hook.adapter.exit_code:x.hook.adapter.error)+'</span><span>'+esc(x.note)+'</span></div>'},b);for(const b of $('harnessRows').querySelectorAll('[data-setup]'))b.onclick=()=>act(async()=>{setupChoice=await api('/api/setup-preview',{harness:b.dataset.setup});$('setupPanel').hidden=false;$('applySetup').hidden=false;$('setupInfo').textContent=[label(setupChoice.harness)+' ('+setupChoice.harness+')','MCP：'+(setupChoice.mcp_action==='preserve'?'保留匹配的现有配置':'用官方 CLI 注册'),'MCP 文件：'+setupChoice.files.mcp,'Hook 文件：'+setupChoice.files.hooks,'共享索引：'+setupChoice.index_home,'新增 Hook：'+(setupChoice.hook_events_added.join('、')||'无，已齐全'),...setupChoice.notes].join('\n');$('applySetup').disabled=!setupChoice.can_apply;$('setupFeedback').textContent=setupChoice.blocker||'待确认；尚未写入配置'},b)}
$('applySetup').onclick=()=>act(async()=>{const x=await api('/api/setup-apply',{harness:setupChoice.harness,revision:setupChoice.revision,confirm:true});setupChoice=null;$('applySetup').hidden=true;await detect();$('setupFeedback').textContent=x.note+' 备份：'+x.backups.map(b=>b.backup).join('；')},$('applySetup'));
$('detectHarnesses').onclick=()=>act(async()=>{await detect();await loadSettings()},$('detectHarnesses'));
$('scanLocal').onclick=()=>act(()=>loadLocal(true),$('scanLocal'));$('localMore').onclick=()=>act(()=>loadLocal(),$('localMore'));
$('filter').oninput=renderIndex;$('refresh').onclick=()=>act(()=>loadIndex(true),$('refresh'));$('more').onclick=()=>act(()=>loadIndex(),$('more'));$('moreNodes').onclick=()=>act(()=>loadNodes(summarySession,false),$('moreNodes'));
for(const side of ['source','target']){$(side+'Harness').onchange=()=>act(()=>loadPicker(side,true));$(side).onchange=updateDeliveryButtons;$(side+'More').onclick=()=>act(()=>loadPicker(side),$(side+'More'))}
$('preview').onclick=()=>act(async()=>{$('previewtext').textContent=(await api('/api/context?session='+q($('source').value))).content},$('preview'));
$('send').onclick=()=>act(async()=>{const x=await api('/api/deliver',{source:$('source').value,target:$('target').value});$('deliveryFeedback').textContent='投递 #'+x.id+' 已排队；原会话与目标保持独立。';await loadReceipts()},$('send'));
const viewNames=['assets','delivery','summary','connection'];function showView(view,updateHash=true){if(!viewNames.includes(view))view='assets';for(const b of document.querySelectorAll('.nav-link')){const active=b.dataset.view===view;b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')}for(const p of document.querySelectorAll('[data-view-panel]'))p.hidden=p.dataset.viewPanel!==view;if(updateHash)history.replaceState(null,'','#'+view);window.scrollTo({top:0,behavior:'instant'})}
for(const b of document.querySelectorAll('.nav-link'))b.onclick=()=>showView(b.dataset.view);window.addEventListener('hashchange',()=>showView(location.hash.slice(1),false));showView(location.hash.slice(1)||'assets');
(async()=>{await detect();await Promise.all([loadIndex(true),loadLocal(true),loadReceipts(),loadSettings()]);updateDeliveryButtons()})().catch(e=>{$('error').textContent=e.message;$('error').hidden=false});
